image: quay.io/fenicsproject/dev-env:latest

pipelines:
  default:
    - step:
        script:
          - pip3 install pytest --upgrade
          - apt-get -y update && apt-get -y install python3-tk
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip3 install git+ssh://git@bitbucket.org/chris_richardson/ffcX.git@master

          - mkdir -p build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Developer ..
          - make -j2
          - make install

          - cd ../demo/documented/poisson/cpp
          - ffc -l dolfin Poisson.ufl
          - cmake . && make && ./demo_poisson
          - cd ../../../..

          - cd python
          - pip3 install .

          - cd test
          - python3 -m pytest unit/geometry/test_bounding_box_tree.py
          - python3 -m pytest unit/io
          - mpirun -n 3 python3 -m pytest unit/io
          - python3 -m pytest unit/la/test_sparsity_pattern.py
          - mpirun -n 3 python3 -m pytest unit/la/test_sparsity_pattern.py
          - python3 -m pytest unit/mesh

          - cd ../demo
          - python3 ./generate-demo-files.py
          - cd documented/poisson
          - export DOLFIN_NOPLOT=1
          - python3 ./demo_poisson.py
          - mpirun -np 3 python3 ./demo_poisson.py
          - cd ../stokes-taylor-hood
          - python3 ./demo_stokes-taylor-hood.py
          - cd ../../undocumented/elasticity
          - python3 demo_elasticity.py
